# Tests to run with workflow-dispatch, pull-request and push events
name: test-ations

on:
  push:
    branches:
      - main

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: ${{ github.event.head_commit.message }}
          title: ${{ github.event.head_commit.message }}
          committer: "${{ github.event.head_commit.committer.name }} <${{ github.event.head_commit.committer.email }}>"
          author: "${{ github.event.head_commit.author.name }} <${{ github.event.head_commit.author.email }}>"
          base: main
          labels: automated-pr
          branch: auto-pr
          delete-branch: false
          push-to-fork: rsanchez15/dev-utils
